import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import db from "@/lib/supabase/db";
import ThemeProvider from "@/lib/providers/next-theme-provider";
import { twMerge } from "tailwind-merge";
const dm_sans = DM_Sans({ subsets: ["latin"] });
import { Toaster } from '@/components/ui/toaster';
import AppStateProvider from "@/lib/providers/state-providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={twMerge("bg-background", dm_sans.className)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AppStateProvider>
            {children}
            <Toaster />
          </AppStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
